//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "components")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub course_id: Uuid,
    pub title: String,
    #[sea_orm(column_type = "Text")]
    pub component_type: String,
    pub code: String,
    pub syllabus_url: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::component_reservations::Entity")]
    ComponentReservations,
    #[sea_orm(
        belongs_to = "super::courses::Entity",
        from = "Column::CourseId",
        to = "super::courses::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Courses,
    #[sea_orm(has_many = "super::evaluations::Entity")]
    Evaluations,
    #[sea_orm(has_many = "super::meetings::Entity")]
    Meetings,
}

impl Related<super::component_reservations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ComponentReservations.def()
    }
}

impl Related<super::courses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Courses.def()
    }
}

impl Related<super::evaluations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Evaluations.def()
    }
}

impl Related<super::meetings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Meetings.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
