//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "instructors")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::evaluations::Entity")]
    Evaluations,
    #[sea_orm(has_many = "super::instructor_meetings::Entity")]
    InstructorMeetings,
}

impl Related<super::evaluations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Evaluations.def()
    }
}

impl Related<super::instructor_meetings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InstructorMeetings.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
