//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "instructor_meetings")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub instructor_id: Uuid,
    pub meeting_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::instructors::Entity",
        from = "Column::InstructorId",
        to = "super::instructors::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Instructors,
    #[sea_orm(
        belongs_to = "super::meetings::Entity",
        from = "Column::MeetingId",
        to = "super::meetings::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Meetings,
}

impl Related<super::instructors::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Instructors.def()
    }
}

impl Related<super::meetings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Meetings.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
