//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

pub use super::component_reservations::Entity as ComponentReservations;
pub use super::components::Entity as Components;
pub use super::courses::Entity as Courses;
pub use super::instructor_meetings::Entity as InstructorMeetings;
pub use super::instructors::Entity as Instructors;
pub use super::meetings::Entity as Meetings;
pub use super::reservations::Entity as Reservations;
