//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "reservations")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub student_type: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub restriction_type: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::component_reservations::Entity")]
    ComponentReservations,
}

impl Related<super::component_reservations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ComponentReservations.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
