[package]
name = "database"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
models = { path = "../models" }
sea-orm = { version = "1.1.13", features = [
    "sqlx-postgres",
    "runtime-tokio-rustls",
    "macros",
] }
